DB_VISUAL_INSPECTION = "visualInspection"

COLLECTION_MODEL_LIST = 'modelList'

COLLECTION_RULE_LIST = "ruleList"

COLLECTION_FILE_UPLOAD_COUNTER = 'fileUploadCounter'
COLLECTION_TRAIN_MODEL_REQUEST_COUNTER = 'trainModelRequestCounter'

COLLECTION_FILE_UPLOAD_REQUEST_DETAILS = 'fileUploadRequest'

COLLECTION_TRAIN_MODEL_REQUEST_DETAILS = "trainModelRequest"

COLLECTION_USER = 'userDetails'

COLLECTION_IMAGE_RECORDS = "imageRecords"

COLLECTION_DOMAIN_DETAILS = "domainDetails"
